name: Gym Manager CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Setup Node
    runs-on: ubuntu-latest
    outputs:
      node_cache_key: ${{ steps.node_cache_key.outputs.cache-hit }}
      java_cache_key: ${{ steps.java_cache_key.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      # Node.js setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        id: node_cache_key
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM dependencies for api
        run: npm install
        working-directory: ./services/api

      - name: Install NPM dependencies for mobile interface
        run: npm install
        working-directory: ./apps/mobile

      - name: Install NPM dependencies for web interface
        run: npm install
        working-directory: ./apps/web

  lint:
  name: Lint API + UI
  runs-on: ubuntu-latest
  needs: setup
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Web UI dependencies
      run: npm install
      working-directory: ./apps/web

    - name: Lint Web UI
      run: npm run lint
      working-directory: ./apps/web


  test:
    name: Run Unit
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install API test deps
        run: npm install
        working-directory: ./services/api

      - name: Run API Tests
        run: npm test
        working-directory: ./services/api

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy API to production
        run: echo "TODO"

      - name: Deploy UI to production
        run: echo "TODO"
