name: Gym Manager CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/api/package-lock.json

      - name: Install API deps
        run: npm ci
        working-directory: ./services/api

      - name: Lint API
        run: npm run lint
        working-directory: ./services/api

  unit-tests:
    name: Run Unit Tests (API)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/api/package-lock.json

      - name: Install API deps
        run: npm ci
        working-directory: ./services/api

      - name: Run API Unit Tests
        run: npm run test:unit
        working-directory: ./services/api
        env:
          JWT_SECRET: ci-unit-secret

  test-availability:
    name: Integration — Availability (/healthz)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/api/package-lock.json

      - name: Install API deps
        run: npm ci
        working-directory: ./services/api

      - name: Run synthetic availability probe
        run: npm run test:integration:availability
        working-directory: ./services/api
        env:
          AVAIL_N: 60
          AVAIL_GAP_MS: 50
          AVAIL_MAX_P95_MS: 300
          AVAIL_MAX_ERR_RATE: 0
          JWT_SECRET: ci-integration-secret

  test-security:
    name: Integration — Security (JWT/Helmet/CORS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/api/package-lock.json

      - name: Install API deps
        run: npm ci
        working-directory: ./services/api

      - name: Run security integration tests
        run: npm run test:integration:security
        working-directory: ./services/api
        env:
          JWT_SECRET: ci-integration-secret

  test-performance:
    name: Integration — Performance (JMeter)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install deps
        run: npm ci

      # No build script? Compile TS directly to dist/
      - name: Compile TypeScript
        run: npx tsc -p tsconfig.json

      - name: Start API and wait for /healthz
        env:
          PORT: 3000
          NODE_ENV: test
          JWT_SECRET: ci-integration-secret
        run: |
          # Start exported Express app from dist/index.js
          node -e "(async()=>{let mod;try{mod=require('./dist/index.js')}catch(e){mod=await import('./dist/index.js')}const app=mod.app||mod.default;if(!app?.listen){console.error('Cannot find exported app');process.exit(1)}const port=process.env.PORT||3000;app.listen(port,()=>console.log('API up on '+port))})()" &
          # Wait until /healthz responds
          for i in {1..40}; do
            curl -fsS "http://localhost:3000/healthz" >/dev/null && break
            sleep 1
          done
          curl -fsS "http://localhost:3000/healthz" >/dev/null || (echo 'API failed to start' && exit 1)

      - name: Install JMeter
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          JM_VERSION=5.6.3
          wget -q https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-$JM_VERSION.zip
          unzip -q apache-jmeter-$JM_VERSION.zip
          echo "$GITHUB_WORKSPACE/apache-jmeter-$JM_VERSION/bin" >> $GITHUB_PATH

      # IMPORTANT: use a local PLAN var, then export outputs for the next step
      - name: Locate JMeter plan
        id: jmx
        run: |
          set -e
          PLAN=""
          OUT=""
          if [ -f tests/perf/healthz.jmx ]; then
            PLAN="tests/perf/healthz.jmx"; OUT="tests/perf/results.jtl"
          elif [ -f src/tests/perf/healthz.jmx ]; then
            PLAN="src/tests/perf/healthz.jmx"; OUT="src/tests/perf/results.jtl"
          else
            echo "Could not find healthz.jmx"
            echo "Tree:"; ls -la
            echo "tests/perf:"; ls -la tests/perf 2>/dev/null || true
            echo "src/tests/perf:"; ls -la src/tests/perf 2>/dev/null || true
            exit 1
          fi
          echo "Using JMX: $PLAN"
          # Optional typo fix if present in your plan
          sed -i 's/Asserion\.test_strings/Assertion.test_strings/g' "$PLAN" || true
          # Export for later steps
          echo "plan=$PLAN" >> "$GITHUB_OUTPUT"
          echo "out=$OUT"   >> "$GITHUB_OUTPUT"

      - name: Run JMeter plan against local API
        env:
          JM_PLAN: ${{ steps.jmx.outputs.plan }}
          JM_OUT:  ${{ steps.jmx.outputs.out }}
          HOST: localhost
          PROTO: http
          PORT: 3000
          users: 10
          ramp: 10
          duration: 30
          MAX_MS: 300
        run: |
          jmeter -n \
            -t "$JM_PLAN" \
            -l "$JM_OUT" \
            -JHOST="$HOST" -JPROTO="$PROTO" -JPORT="$PORT" \
            -Jusers="$users" -Jramp="$ramp" -Jduration="$duration" -JMAX_MS="$MAX_MS"

      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: ${{ steps.jmx.outputs.out }}

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, test-availability, test-security, test-performance]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy API to production
        run: echo "TODO"
      - name: Deploy UI to production
        run: echo "TODO"
