name: Gym Manager CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/api/package-lock.json

      - name: Install API deps
        run: npm ci
        working-directory: ./services/api

      - name: Lint API
        run: npm run lint
        working-directory: ./services/api

  unit-tests:
    name: Run Unit Tests (API)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/api/package-lock.json

      - name: Install API deps
        run: npm ci
        working-directory: ./services/api

      - name: Run API Unit Tests
        run: npm run test:unit
        working-directory: ./services/api
        env:
          # Provide a dummy secret so JWT-related unit tests don’t explode
          JWT_SECRET: ci-unit-secret

  test-availability:
    name: Integration — Availability (/healthz)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/api/package-lock.json

      - name: Install API deps
        run: npm ci
        working-directory: ./services/api

      - name: Run synthetic availability probe
        run: npm run test:integration:availability
        working-directory: ./services/api
        env:
          AVAIL_N: 60
          AVAIL_GAP_MS: 50
          AVAIL_MAX_P95_MS: 300
          AVAIL_MAX_ERR_RATE: 0
          JWT_SECRET: ci-integration-secret

  test-security:
    name: Integration — Security (JWT/Helmet/CORS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: services/api/package-lock.json

      - name: Install API deps
        run: npm ci
        working-directory: ./services/api

      - name: Run security integration tests
        run: npm run test:integration:security
        working-directory: ./services/api
        env:
          JWT_SECRET: ci-integration-secret

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, test-availability, test-security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy API to production
        run: echo "TODO"

      - name: Deploy UI to production
        run: echo "TODO"
